// <auto-generated />
namespace Download.MigrationData.ProductMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class AddingExFilesStatus : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddingExFilesStatus));
        
        string IMigrationMetadata.Id
        {
            get { return "201406272101267_AddingExFilesStatus"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
