// <auto-generated />
namespace Download.MigrationData.ProductMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class AddingFileSize : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddingFileSize));
        
        string IMigrationMetadata.Id
        {
            get { return "201406271528489_AddingFileSize"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
